name: macOS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Print Swift version
      run: swift --version

    - name: Build
      run: swift build -v

    - name: Run tests
      run: swift test
