name: macOS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    = name: Print Swift version
      run: swift --version
    - name: Build and run tests
      run: swift test
