# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Ubuntu

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: swift-actions/setup-swift@v2.0.0
      with:
        # Swift version to configure
        swift-version: "5.10.1"
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
