name: Ubuntu

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: sinoru/actions-setup-swift@v2.2.0
      with:
        swift-version: '5.6.0'
    - name: Build and run tests
      run: swift test -v --enable-code-coverage
    - name: Test coverage
      uses: maxep/spm-lcov-action@0.3.1
