# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Ubuntu

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install curl
      run: sudo apt install -y curl
    - name: Add Swift repo
      run: curl -s https://archive.swiftlang.xyz/install.sh | sudo bash
    - name: Install swift
      run: sudo apt install swiftlang
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
